### ISSUE TITLE
Old android device using ro.product.cpu.abi rather than ro.product.cpu.abilist

### ISSUE THREAD

**Issue by jtempest** [sonos/dinghy#109]
First off, nice job with dinghy! It seems really handy.

I'm trying to use it to run tests on an old Samsung S4 Mini. Out of the box it doesn't work, failing with:

> \> cargo dinghy -d android test
> ERROR cargo_dinghy > Error: No device and platform combination found for device hint `android'

After a bit of googling, on a hunch I cloned the repo and did a local build, and got it working with two changes to `android/device.rs`:

line 25: `"ro.product.cpu.abilist"` to `"ro.product.cpu.abi"`
line 34: `"armv7-linux-androideabi"` to `"arm-linux-androideabi"`

Using NDK 21.0.6113669 installed via an Android Studio I installed today. 

I literally just got into android development, so I'm not sure if you could do a fallback to look for the older key if the lookup fails or the implications of changing that triple, but do you think it might be possible to add this support more generally?

**Comment by kali** [comment]
Hi ! thanks for your interest in dinghy !

I think the old branch #91 have what you need. It was left behind for no good reason. I have rebased it against the master, would you like to give it a try ?

I am sorry I can't try it on my own. I'm quantantined and I don't have any android device at my place.

**Comment by jtempest** [comment]
Gave it a try, it all just works :)

**Comment by kali** [comment]
Thanks, i have merged the branch. Leaving this open till the branch is merged.
