### ISSUE TITLE
Dinghy on Linux

### ISSUE THREAD

**Issue by kafji** [sonos/dinghy#121]
Hi, I had trouble when using Dinghy on Linux. After a couple hours of debugging I found 2 issues:

1. It seem the path to Android NDK is different on Linux (or did they change it? I don't remember). I installed the NDK using Android Studio SDK manager, and it puts the NDK at `$ANDROID_SDK_ROOT/ndk/21.3.6528147` where `21.3.6528147` is the NDK version. It looks like you can install multiple versions of NDK from the SDK manager now.\
\
Since the NDK location is different than [what Dinghy expected](https://github.com/sonos/dinghy/blob/main/dinghy-lib/src/android/mod.rs#L182-L186), Dinghy fails to guess the NDK location.

2. When Dinghy fails to guess the location of NDK it would assume that Android platforms is non existent without warning. Eventhough it found Android SDK and found that there is an Android emulator connected.

The workaround is to explicitly set the NDK location for Dinghy:
```
export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/21.3.6528147
```

But I think there are few improvements that can be made:

For the first issue, I'm not sure if it is Linux specific or it just the new default path for NDK. I think we should also check if NDK exist there.

For the second issue, I think we should also print out a message when Dinghy did not found the NDK location when the verbose flag is specified.

What do you think?

**Comment by kali** [comment]
I agree on both points. Since this is very environment dependent, the easier way to proceed is probably for you to make a PR. It should be pretty straightforward, you've already find where the relevant bit of code :)

**Comment by kafji** [comment]
Ok. I'll start working on it.

That path is indeed the new default location for NDK. https://developer.android.com/studio/projects/install-ndk

**Comment by kafji** [comment]
PRs merged. I'm closing this.

Thank you.

**Comment by kali** [comment]
you're welcome ! release on the way.
