### ISSUE TITLE
Cannot run tests on iOS 14 device

### ISSUE THREAD

**Issue by Robert-Steiner** [sonos/dinghy#131]
Hi,
When I tried to run my test with the command `cargo dinghy -d iphone test` I got the following error:

```
[2021-03-15T14:19:28Z ERROR cargo_dinghy] error: e8000022
```

I get the same error when I run `cargo dinghy -d iphone lldbproxy`.
My package compiles without problems. I guess it is related to this https://github.com/ios-control/ios-deploy/issues/469#issuecomment-678552777.

Specs:
- iPhone 8, iOS 14.4.1
- macOS 11.2.2, Xcode 12.4

**Comment by simlay** [comment]
This is with the iOS simulator or an actual device?

**Comment by Robert-Steiner** [comment]
I used an actual device

**Comment by umgefahren** [comment]
Any updates on this?

**Comment by umgefahren** [comment]
Any updates on this?

**Comment by ZhaoXiangXML** [comment]
I got the same error on iOS 15. The app can be tested with iOS-deploy.

**Comment by fredszaq** [comment]
with https://github.com/sonos/dinghy/issues/166 we now use ios-deploy directly, this fixes the problem
