### ISSUE TITLE
No more working on iOS devices 14.x

### ISSUE THREAD

**Issue by EliseChouleur** [sonos/dinghy#135]
Hi,

The current version of the project isn't working on latest version of Xcode and iOS devices.

I managed to correct some bugs as the certificate management where "ON=" is now "ON = ", but I'm now struggling with lldb which can't connect to the platform and it seems to be linked to a device error which is: `Unable to generate launch image for fr.doctolib.pro.dev.Dinghy because the app has no valid launch interfaces.`

I have no concrete issue but I was wondering if a support of latest Xcode and iOS plateform were planned.
If it's the case I could share what I already tried to correct.

Thanks a lot !

**Comment by kali** [comment]
Dinghy is in maintenance mode, but not abandonned. As long as we managed to keep iOS working reasonably, we will do it. We just don't have much bandwidth for it.

So please, feel welcome to share what you've already done :) Maybe we will find a bit of time, or somebody will pick from where you are.

To go beyond that, well, LLDB is a total mess. A good source for inspiration is to look at https://github.com/ios-control/ios-deploy and port whatever machinery and tricks they found out.

**Comment by fredszaq** [comment]
with #166 we now use `ios-deploy` directly, this fixes the problem
