### ISSUE TITLE
tvOS simulator support

### ISSUE THREAD

**Issue by simlay** [sonos/dinghy#193]
[tvOS is currently a tier 3 target](https://doc.rust-lang.org/nightly/rustc/platform-support/apple-tvos.html) but it's still plausible to update dinghy to work similar to the iOS simulator.

I believe one can just use [xcrun to install launch and run an app on an tvOS or watchOS simulator just like with the iOS simulator](https://github.com/sonos/dinghy/blob/ad80bc4a1cf6aa47aec0534e0514c08dc8f685c2/dinghy-lib/src/ios/device.rs#L375-L463).

One would unfortunately still probably have to use [lldb to get the exit code of the program in the simulator](https://github.com/sonos/dinghy/blob/ad80bc4a1cf6aa47aec0534e0514c08dc8f685c2/dinghy-lib/src/ios/device.rs#L465-L513).

**Comment by kali** [comment]
I guess we can close this one ?
