### ISSUE TITLE
Getting files generated by tests back?

### ISSUE THREAD

**Issue by torokati44** [sonos/dinghy#199]
I really like that dinghy magically packs up every file that the tests need, and yeets them over to the device running the tests!

Now I'd like a way to get the files (in this case, actual visual output, and image difference from expected output) created by the failed tests back onto my computer - the same way as I would have them when running the tests on it natively.

Is there a way to access the files written by the tests now, and would you consider adding an option to sync them back into the source tree automatically?

**Comment by torokati44** [comment]
Just to answer one of my own questions right away:
All I really needed to do was `adb pull /data/local/tmp/dinghy`, and I got my files after running the tests... :sweat_smile:

**Comment by fredszaq** [comment]
Yes that would be the easiest way :P,, closing then!

**Comment by torokati44** [comment]
Alright! While I was able to get the files I wanted, I still think it would be nice to have an easy way for this built in.
Or at least the `adb pull` method mentioned in the docs somewhere - I had to fish out the on-device working directory from somewhere in the code.
But I'm not gonna reopen just for this. :)
