### ISSUE TITLE
Use `xcrun devicectl` to deploy to iOS devices.

### ISSUE THREAD

**Issue by simlay** [sonos/dinghy#204]
Looks like `ios-deploy` has issues with `Xcode 15`. https://github.com/ios-control/ios-deploy/issues/588

[Xcode 15 added a new tool `xcrun devicectl`](https://developer.apple.com/documentation/updates/xcode#Tuning-and-debugging) which is similar to `xcrun simctl` but for physical devices. Though, it doesn't work with older devices - I've got an iphone 5 that doesn't list with `xcrun devicectl list devices`.

**Comment by kali** [comment]
I had a look, and this is a very sad mess. `devicectl` will just let us start the app. There is no way to capture output or the app return code. And it looks like the ios-deploy folks have more or less give up.

At this stage, I can't see any "clean" way out of this. Nothing that does not rely on super hacky stdout/stderr capture from within the app... or something from within the app.

This is very sad. Apple has waited nearly 20 years to provide half of a solution to a problem they created, and managed to break the third-party solution doing so.

**Comment by kali** [comment]
There may be part of a solution here https://github.com/ios-control/ios-deploy/issues/588#issuecomment-1907913430

Basically we would have to switch ios-deploy for https://github.com/doronz88/pymobiledevice3 and try to replug everything back together. And hope Apple does not break it again in three months...
