### ISSUE TITLE
cargo install dinghy takes too long

### ISSUE THREAD

**Issue by gnzlbg** [sonos/dinghy#39]
I don't know if something can be done about this (if `dinghy` must depend on `cargo` then probably not), but it currently takes ~7 minutes to `cargo install dinghy` in travis-ci. One can use Travis `cache: cargo`  as a workaround, but there must be a better way.

**Comment by kali** [comment]
We may be able to sever the hard coupling with cargo, but it's a bit of a refactoring, so we need to make sure it can actually be done before commiting to it. If some bits are missing, we may need to submit patches to cargo too.

**Comment by gnzlbg** [comment]
What exactly do you need from cargo? `cargo metadata` might provide some of it, but not all of it unfortunately :/

**Comment by kali** [comment]
That's the point really. We need an inventory of what we need, and find out which bits, if any, are missing. I think I remember that last time I looked at this, there was one bit of info that was tough to obtain (I don't remember what), so I decided... "Later."

**Comment by fredszaq** [comment]
#157 was merged and fixes this
